# Generated by Django 6.0.1 on 2026-02-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='inquiries/'),
        ),
    ]
